Restaurant/Controllers/AdminOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Restaurant.Models;
using System.Data;

namespace Restaurant.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminOrderController : Controller
    {
        protected readonly RestaurantContext _context;


        public AdminOrderController(RestaurantContext c)
        {
            _context = c;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var orders = await _context.orders.Include("OrderItems")
               .Include("OrderItems.Product")
               .ToListAsync();

            var model = new ListOfOrderTotalModels();
            foreach (var order in orders)
            {
                var total = order.OrderItems.Sum(x => x.TotalPrice);
                model.Add(new OrderTotalModel { Total = total, Order = order });
            }


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatus(string action, int id)
        {
            var status = action;
            var order = await _context.orders.FirstOrDefaultAsync(z => z.OrderId == id);

            order.Status = status;

            await _context.SaveChangesAsync();

            return RedirectToAction("AccessDenied", "Account");
        }



    }
}

Restaurant/Controllers/AdminUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Restaurant.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminUserController : Controller
    {
        protected readonly RestaurantContext _context;


        public AdminUserController(RestaurantContext c)
        {
            _context = c;
        }

            [HttpGet]
        public async Task<IActionResult> Index()
        {
            var users = await _context.users.ToListAsync();

            return View(users); ;
        }
    }
}

Restaurant/Controllers/OrderController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Restaurant.Models;
using Restaurant.Services;
using System.Net;

namespace Restaurant.Controllers
{
    public class OrderController : Controller
    {

        protected readonly RestaurantContext _context;
        private readonly BasketHelper _basketHelper;

        public OrderController(RestaurantContext c, BasketHelper basketHelper)
        {

            _context = c;
            _basketHelper = basketHelper;

        }
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateOrder(OrderModel model)
        {






            var userName = User.Identity.Name;
            var user = await _context.users.FirstOrDefaultAsync(z => z.UserEmail == userName);
            var items = await _basketHelper.LoadBasket(userName);
            var status = "Getorder";
            var order = new Order()
            {
                Name = model.name,
                Street = model.street,
                House = model.house,
                Flat = model.flat,
                Phone = model.phone,
                Descriprion = model.description,
                Status = status,
                User = user

            };
          

            var userAdresses = await _context.userAddresses.FirstOrDefaultAsync(z => z.User == user);
            if (userAdresses == null)
            {
                var userAdress = new UserAddress()
                {
                    User = user,
                    Street = model.street,
                    House = model.house,
                    Flat = model.flat
                };
                _context.userAddresses.Add(userAdress);
            }
            else
            {


                if (userAdresses.Street != model.street || userAdresses.House != model.house || userAdresses.Flat != model.flat)
                {


                    var userAdress = new UserAddress()
                    {
                        User = user,
                        Street = model.street,
                        House = model.house,
                        Flat = model.flat
                    };
                    _context.userAddresses.Add(userAdress);
                }
            }

            foreach (var item in items.basket)
            {

                var basketProduct = await _context.products.FirstOrDefaultAsync(z => z.ProductId == item.ProductId);



                var orderItem = new OrderItem()
                {
                    Quantity = item.Quantity,

                    Product = basketProduct,
                    PricePerItem = item.PricePerItem,
                    TotalPrice = item.TotalPrice
                };

                var bonus = 0.0m;
                order.OrderItems.Add(orderItem);


             
                if(item.TotalPrice >= 8 && item.TotalPrice <= 14)
                {
                    bonus = item.TotalPrice / 100 * 10;
                }
                else if (item.TotalPrice >= 15 && item.TotalPrice <= 24)
                {
                    bonus = item.TotalPrice / 100 * 15;
                }
                else if (item.TotalPrice >= 25 )
                {
                    bonus = item.TotalPrice / 100 * 20;
                }
                else
                {
                    bonus = 1;
                }

          
                if (user.Bonuses is null)
                    user.Bonuses = bonus;
                else
                    user.Bonuses += bonus;

            }


           
            _context.orders.Add(order);

            await _context.SaveChangesAsync();
            foreach (var item in items.basket)
            {
                _context.baskets.Remove(item);
            }
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Account");

        }
    }
}

Restaurant/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Restaurant.Controllers
{
    public class ProductController : ProductBaseController
    {
        public ProductController(RestaurantContext c) : base(c)
        {
        }

        public IActionResult Index()
        {
            return View();
        }
     


    

      
        [HttpGet]
        public async Task<IActionResult> Index(char category)
        {
            var productCategory = await _context.products.Where(z => z.Category == category).ToListAsync();
            return View(productCategory);
        }

        [HttpGet]
        public async Task<IActionResult> ShowDetails( int id)
        {
            List<Product> product;
             product = await _context.products.Where(z => z.ProductId == id).ToListAsync();
        
         
            return View(product);
        }

        [HttpGet]
        public async Task<IActionResult> ShowRandomProduct()
        {
            List<int> products;
   

            products = await _context.products.Select(z => z.ProductId).ToListAsync();

            Random r = new Random();

            var randomValues = Enumerable.Range(0, 2).Select(e => products[r.Next(products.Count)]);

            var items = await _context.products.Where(z => randomValues.Contains(z.ProductId)).ToListAsync();
            return Json(items);
        }


    }
}

Restaurant/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;
using System.Security.Claims;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace Restaurant.Controllers
{
    public class UserController : Controller
    {

        private readonly RestaurantContext _context;
        private readonly IConfiguration _configuration; 
        public UserController(RestaurantContext c, IConfiguration config)
        {

            _context = c;
            _configuration = config;

        }
        public IActionResult ShowLogin()
        {
            return View();
        }



        public IActionResult ShowRegistration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRegistration(RegistrationModel model)
        {


            var cheakUsers = await _context.users.FirstOrDefaultAsync(z => z.UserEmail == model.email) ;
            if (cheakUsers == null)
            {
                if (model.password == model.password2)
                {

                    byte[] salt = new byte[128 / 8];
                    using (RandomNumberGenerator rnd = RandomNumberGenerator.Create())
                        rnd.GetBytes(salt);


                    string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: model.password,
                        salt: salt,
                        prf: KeyDerivationPrf.HMACSHA256,
                        iterationCount: 100000,
                        numBytesRequested: 256 / 8));
                    hashed += "~";
                    hashed += Convert.ToBase64String(salt);

                    _context.users.Add(new User()
                    {
                        UserEmail = model.email,
                        UserPassword = hashed
                    });
                    _context.SaveChanges();
                    return RedirectToAction("ShowLogin");
                }

                else
                {
                    TempData["LoginError"] = "password no nice";
                    return RedirectToAction("ShowRegistration");
                }
            }
            else
            {
                TempData["LoginError"] = " phone already used";
                return RedirectToAction("ShowRegistration");

            }
        }

        [HttpPost]
        public async Task<IActionResult> GoToAccount(LoginModel model)
        {
            var user = _context.users.FirstOrDefault(z => z.UserEmail== model.email);
            if (user == null)
            {
                TempData["Error"] = "no correct password or email";
                return RedirectToAction("ShowLogin");

            }

            string[] records = user.UserPassword.Split('~'); 
            byte[] salt = Convert.FromBase64String(records[1]);
            string passwordHash = records[0];

            string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                password: model.password,
                salt: salt,
                prf: KeyDerivationPrf.HMACSHA256,
                iterationCount: 100000,
                numBytesRequested: 256 / 8));

            if (hashed == passwordHash)
            {
            

                List<Claim> claims = new();
                claims.Add(new Claim("sub", model.email));
                claims.Add(new Claim(ClaimTypes.Name, model.email));

                string adminAccount = _configuration["AdminAccount"]; 

                var isAdmin = user.UserEmail == adminAccount; 
                if (isAdmin)
                {
                    claims.Add(new Claim(ClaimTypes.Role, "admin"));

                }
               

                await HttpContext.SignInAsync(
                    new System.Security.Claims.ClaimsPrincipal(new ClaimsIdentity(
                         claims, CookieAuthenticationDefaults.AuthenticationScheme)), new AuthenticationProperties()
                         {

                         });

                //if (isAdmin)
                //    return RedirectToAction("Index", "AdminProduct");
                //else

                    return RedirectToAction("Index", "Account");



            }
            else
            {
                TempData["Error"] = "no correct password or email";
                return RedirectToAction("ShowLogin");


            }
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }


    }



}

Restaurant/Views/Shared/_Layout.cshtml
@using Restaurant;


<!DOCTYPE html>

<html>
<head>
    <link href="~/css/layout.css" rel="stylesheet" />
    <link href="~/css/basket.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/jquery/jquery-ui.css" rel="stylesheet" />
<script src="~/jquery/jquery.js"></script>
<script src="~/jquery/jquery-ui.js"></script>
  @RenderSection("CssAndScript", false)

</head>
<body>
    <div class="boxSite">

        <div class="container">
            <div class="menu">
                <div class="buttons">
                    <button class="buttonBasketShow"><img class="buttonBasketShowImg" src="~/pictures/—Pngtree—shopping cart icon_5060874.png" /></button>
                    <button class="addToOrder"><a asp-controller="Order" asp-action="Index">Go To Order</a></button>
                </div>
                <div class="basketStuff"></div>
       
            </div>
        </div>
        <div class="header">
            <div class="menu1"></div>
            <div class="headLinks">
                <div class="siteLink">
                    <a asp-controller="Home" asp-action="Index">JustFood</a>
                </div>
                <div class="delivery">
                    Delivery and pay
                </div>
                @if (User.IsInRole("admin"))
                {
                    <a class="adminSide" asp-controller="AdminProduct" asp-action="Index">Admin Side</a>
                }
                else
                {
                    <div></div>
                }
               
                <div class="contact">
                    Contacts
                </div>
                <div class="about">
                    About
                </div>
                <div class="account">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a asp-controller="Account" asp-action="Index">Go Account</a>
                    }
                    else
                    {
                        <a asp-controller="User" asp-action="ShowLogin">Go Account</a>
                    }

                </div>

            </div>

            <div class="headMenu">

                <div class="salads">
                    <a asp-controller="Product" asp-action="Index" asp-route-category="s">Salads</a>
                </div>
                <div class="pizza">
                    <a asp-controller="Product" asp-action="Index" asp-route-category="p">Pizza</a>
                </div>
                <div class="wok">
                    <a asp-controller="Product" asp-action="Index" asp-route-category="w">WOK</a>
                </div>
                <div class="desserts">
                    <a asp-controller="Product" asp-action="Index" asp-route-category="d">Desserts</a>
                </div>
                <div class="drinks">
                    <a asp-controller="Product" asp-action="Index" asp-route-category="r">Drinks</a>
                </div>
            </div>
            <div class="menu2"></div>
        </div>

        <div class="side1"></div>
        <div class="main">
            @RenderBody()
        </div>
        <div class="side2"></div>


        <div class="footer">
            <div class="col1">
                <div class="itemFooterName">Catalogs</div>
                <div class="footerMenu">
                    <div class="categoryMeal">
                        <a asp-controller="Product" asp-action="Index" asp-route-category="s">Salads</a>
                    </div>
                    <div class="categoryMeal">
                        <a asp-controller="Product" asp-action="Index" asp-route-category="p">Pizza</a>
                    </div>
                    <div class="categoryMeal">
                        <a asp-controller="Product" asp-action="Index" asp-route-category="w">WOK</a>
                    </div>
                    <div class="categoryMeal">
                        <a asp-controller="Product" asp-action="Index" asp-route-category="d">Desserts</a>
                    </div>
                    <div class="categoryMeal">
                        <a asp-controller="Product" asp-action="Index" asp-route-category="r">Drinks</a>
                    </div>
                </div>

            </div>

            <div class="col2">
                <div class="itemFooterName">Company</div>
                <div class="itemFooter">About</div>
                <div class="itemFooter">Delivery and pay</div>
                <div class="itemFooter">Bonuses</div>
                <div class="itemFooter">Vacantion</div>
            </div>
            <div class="col3">
                <div class="itemFooterName">Contacts</div>
                <div class="itemFooter">Phones for Delivery:</div>
                <div class="itemFooter">09988775543</div>
                <div class="itemFooter">09888775543</div>
                <div class="itemFooter">09388775543</div>
                <div class="itemFooter">Phone for complaints:</div>
                <div class="itemFooter">09388775635</div>
            </div>
            <div class="col4">
                <div class="complaint">Complaint</div>
                </div>
        </div>

    </div>





<script>
    $(document).ready(() => {
        $.ajax({
            type: "GET",
            url: "/Basket/LoadBasket",
            dataType: "html",
            success: function (html) {
                RenderBasket(html);
            }
        });
    });
   


    $(document).ready(function () {
        $(".buttonBasketShow").mouseenter(function () {
            $(".container").toggleClass("open");
        });
    });


        function DeleteBasketProduct(Id) {
            $.ajax({
                type: "POST",
                url: "/Basket/DeleteBasketProduct",
                data: { "id": Id },
                dataType: "html",
                success: function (result) {
    
                    RenderBasket(result);
                }

            });
        }
        //this your show html shared f
        function RenderBasket(html){
            $(".basketStuff").html(html); //so this no good?
   
         
        }

        function ChangeQuantity(Id,action){
            $.ajax({
                type: "POST",
                url: "/Basket/ChangeQuantity",
                data: { "id": Id, "action": action },
                dataType: "html",
                success: function (result) {
                    RenderBasket(result);
                }

            });
        }

</script>
</body>
</html>

Restaurant/Views/Shared/_Layout1.cshtml
@{

    Layout = "_Layout";

    }
@section CssAndScript {
    @RenderSection("CssAndScript", false)

}
<link href="~/css/layout1.css" rel="stylesheet" />


    <div class="adminLinks">
        <a asp-controller="AdminProduct" asp-action="Index">GoToProduct</a>
        <a asp-controller="AdminUser" asp-action="Index">GoToUser</a>
        <a asp-controller="AdminOrder" asp-action="Index">GoToOrder</a>
    </div>
    <div>
        @RenderBody()
    </div>
 

Restaurant/Views/Shared/_Layout2.cshtml
@{

    Layout = "_Layout";

}
@section CssAndScript {
    @RenderSection("CssAndScript", false)
    <link href="~/css/layout2.css" rel="stylesheet" />
}


<div class="box">
    <div class="leftMenu">
    <div class="menuItem"> <a asp-controller="Account" asp-action="Index">My Info</a></div>
    <div class="menuItem"> <a asp-controller="Account" asp-action="ShowAddresses">My Adresses</a></div>
    <div class="menuItem"><a asp-controller="Account" asp-action="ShowOrders">My Orders</a></div>
    <div class="menuItem">item3</div>
    <div class="menuItem">item4</div>
    <div class="menuItem">item5</div>
    </div>
<div>
    @RenderBody()
</div>
</div>

Restaurant/Views/Shared/_Order.cshtml
@using Restaurant;
@using Restaurant.Models;
@model List<OrderTotalModel>;


<div class="tableContainer">

    <div class="eachRow headerRow">
        <div class="cell">Order ID</div>
        <div class="cell">Name</div>
        <div class="cell">Phone</div>
        <div class="cell"> Total Price</div>
    </div>

    @foreach (var item in Model)
    {
        <div class="eachRow">
            <div id="@item.Order.OrderId" class="cell orderId">
                <img class="bottom" src="~/pictures/bottom.png" />
                @item.Order.OrderId
            </div>
            <div class="cell">@item.Order.Name</div>
            <div class="cell">@item.Order.Phone</div>
            <div class="cell">@item.Total</div>
        </div>

        <div class="contentOrder" id="@string.Concat("content", item.Order.OrderId)">
            <div class="orderItemsContainer">
                <div class="eachRowTwo headerRowTwo">
                    <div class="cellTwo">Item ID</div>
                    <div class="cellTwo">Product</div>
                    <div class="cellTwo">Quantity</div>
                    <div class="cellTwo"> Price Per Item</div>
                </div>
                @foreach (var orderItem in @item.Order.OrderItems)
                {
                    <div class="eachRowTwo eachOrderItem">
                        <div class="cellTwo">@orderItem.OrderItemId</div>
                        <div class="cellTwo">@orderItem.Product.ProductName</div>
                        <div class="cellTwo">@orderItem.Quantity</div>
                        <div class="cellTwo">@orderItem.TotalPrice</div>
                    </div>
                }
            </div>
            <div class="buttonsStatus">
                <button onclick="ChangeStatus(@item.Order.OrderId, 'Getorder')" class="buttonStatus" >Get</button>
                <button onclick="ChangeStatus(@item.Order.OrderId, 'Incooking')" class="buttonStatus" >In work</button>
                <button onclick="ChangeStatus(@item.Order.OrderId, 'Delivery')" class="buttonStatus">Delivery</button>
                <button onclick="ChangeStatus(@item.Order.OrderId, 'Done')" class="buttonStatus" >Done</button>
            </div>
        </div>

    }

</div>